# Generated by Django 5.1.6 on 2025-02-07 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_reference', models.CharField(max_length=100, unique=True, verbose_name='Référence Transaction')),
                ('flutterwave_transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Transaction Flutterwave')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant')),
                ('currency', models.CharField(default='USD', max_length=5, verbose_name='Devise')),
                ('status', models.CharField(choices=[('INITIATED', 'Transaction Initiée'), ('PENDING', 'En Attente'), ('SUCCESSFUL', 'Succès'), ('FAILED', 'Échec'), ('REFUNDED', 'Remboursé')], default='INITIATED', max_length=20, verbose_name='Statut')),
                ('payment_method', models.CharField(blank=True, choices=[('CARD', 'Carte Bancaire'), ('BANK_TRANSFER', 'Virement Bancaire'), ('MOBILE_MONEY', 'Mobile Money'), ('USSD', 'USSD')], max_length=20, null=True, verbose_name='Méthode de Paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Mise à Jour')),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Client')),
                ('raw_response', models.JSONField(blank=True, null=True, verbose_name='Réponse Brute')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Transaction de Paiement',
                'verbose_name_plural': 'Transactions de Paiement',
                'ordering': ['-created_at'],
            },
        ),
    ]
